name: "Setup Senzing Playground"
description: "Setup Senzing Playground (Install SDK & Setup Data Dir)"
runs:
  using: "composite"
  steps:
    - name: Install Senzing API
      uses: senzing-factory/github-action-install-senzing-api@v3
      with:
        senzingapi-runtime-version: production-v3
    - name: Install Senzing SDK & Data
      run: sudo --preserve-env apt-get install -y senzingapi senzingdata-v5
      env:
        SENZING_ACCEPT_EULA: I_ACCEPT_THE_SENZING_EULA
      shell: bash
    - name: Setup Senzing Data Directory
      run: python3 /opt/senzing/g2/python/G2CreateProject.py ~/senzing
      shell: bash
    - name: Load Senzing Env Variables
      run: |
        source ~/senzing/setupEnv

        echo "SENZING_ROOT=$SENZING_ROOT" >> $GITHUB_ENV
        echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "CLASSPATH=$CLASSPATH" >> $GITHUB_ENV
      shell: bash
    - name: Setup Base Senzing Config
      run: echo yes | python3 ~/senzing/python/G2SetupConfig.py
      shell: bash
