name: "Setup Application Runtime Environment"
description: "Setup Application Runtime Environment"
inputs:
  mix-env:
    description: "Mix environment to use"
    required: false
    default: "dev"
runs:
  using: "composite"
  steps:
    - uses: erlef/setup-elixir@v1
      id: setupBEAM
      with:
        version-file: .tool-versions
        version-type: strict

    - name: Cache Build Directory
      uses: actions/cache@v4
      with:
        path: _build
        key: "${{ format('{0}-build-{1}-{2}', inputs.mix-env, hashFiles('.tool-versions'), hashFiles('mix.exs')) }}"
        restore-keys: "${{ format('{0}-build-{1}-', inputs.mix-env, hashFiles('.tool-versions')) }}"
    - name: "Cache Dependencies"
      uses: actions/cache@v4
      with:
        path: deps
        key: "${{ format('{0}-deps-{1}-{2}', inputs.mix-env, hashFiles('.tool-versions'), hashFiles('mix.exs')) }}"
        restore-keys: "${{ format('{0}-deps-{1}-', inputs.mix-env, hashFiles('.tool-versions')) }}"
    - name: "Cache Zig Binary"
      uses: actions/cache@v4
      with:
        path: ~/.cache/zigler
        key: "${{ format('zigler-{0}', hashFiles('mix.exs')) }}"
        restore-keys: "zigler-"

    - name: "Install Dependencies"
      run: mix deps.get --check-locked
      shell: bash

    - name: "Install Zig"
      run: mix zig.get
      shell: bash
