on:
  push:
    branches:
      - "main"

name: "Main Branch"

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml

  docs:
    name: "Docs"

    uses: ./.github/workflows/part_docs.yml

  publish:
    name: "Publish"

    uses: ./.github/workflows/part_publish.yml
