on:
  workflow_call:
    inputs:
      releaseName:
        required: false
        type: string

name: "Documentation"

jobs:
  generate:
    name: "Generate"

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: "Setup Runtime Environment"
        uses: ./.github/actions/setup-runtime-env
        id: setupRuntimeEnv

      - uses: ./.github/actions/setup-senzing-playground

      - run: mix docs
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: doc

  upload:
    name: "Upload"

    runs-on: ubuntu-latest

    if: ${{ inputs.releaseName }}

    needs: ["generate"]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs
      - run: |
          tar -czvf docs.tar.gz docs
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload --clobber "${{ inputs.releaseName }}" \
            docs.tar.gz
