on:
  workflow_call:
    inputs:
      releaseName:
        required: false
        type: string
    secrets:
      HEX_API_KEY:
        required: false

name: "Publish"

jobs:
  hex_publish:
    name: mix hex.publish

    runs-on: ubuntu-latest

    if: "${{ inputs.releaseName }}"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: "Setup Runtime Environment"
        uses: ./.github/actions/setup-runtime-env
        id: setupRuntimeEnv

      - run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

  hex_build:
    name: mix hex.build

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: "Setup Runtime Environment"
        uses: ./.github/actions/setup-runtime-env
        id: setupRuntimeEnv

      - run: mix hex.build --output package.tar
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: package.tar

  upload:
    name: "Upload"

    runs-on: ubuntu-latest

    if: ${{ inputs.releaseName }}

    needs: ["hex_build"]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: package
          path: .
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload --clobber "${{ inputs.releaseName }}" \
            package.tar
