on:
  workflow_call: {}

name: "Test"

jobs:
  detectToolVersions:
    name: "Detect Tool Versions"

    runs-on: ubuntu-latest

    outputs:
      otpVersion: "${{ steps.toolVersions.outputs.OTP_VERSION }}"
      elixirVersion: "${{ steps.toolVersions.outputs.ELIXIR_VERSION }}"

    steps:
      - uses: actions/checkout@v4
      - name: "Read .tool-versions"
        id: toolVersions
        run: |
          OTP_VERSION="$(cat .tool-versions | grep erlang | cut -d' ' -f2-)"
          echo OTP: $OTP_VERSION
          echo "OTP_VERSION=${OTP_VERSION}" >> $GITHUB_OUTPUT

          ELIXIR_VERSION="$(cat .tool-versions | grep elixir | cut -d' ' -f2-)"
          echo Rebar: $ELIXIR_VERSION
          echo "ELIXIR_VERSION=${ELIXIR_VERSION}" >> $GITHUB_OUTPUT

  mix_format:
    name: mix format

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: "Setup Runtime Environment"
        uses: ./.github/actions/setup-runtime-env
        id: setupRuntimeEnv

      - run: mix format --check-formatted

  mix_test:
    name: mix test (${{ matrix.elixir }})

    runs-on: ubuntu-latest

    needs: ["detectToolVersions"]

    strategy:
      fail-fast: false
      matrix:
        include:
          # Lowest Supported Version
          - elixir: "1.17.0"
            otp: "27.0"
            unstable: false
          # Latest Supported Version (via ASDF)
          - elixir: "${{ needs.detectToolVersions.outputs.elixirVersion }}"
            otp: "${{ needs.detectToolVersions.outputs.otpVersion }}"
            unstable: false
          # Elixir Main
          - elixir: "main"
            otp: "${{ needs.detectToolVersions.outputs.otpVersion }}"
            unstable: true

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          otp-version: "${{ matrix.otp }}"
          elixir-version: "${{ matrix.elixir }}"
          version-type: strict

      - uses: ./.github/actions/setup-senzing-playground

      - name: Cache Build Directory
        uses: actions/cache@v4
        with:
          path: _build
          key: "${{ format('test-build-{0}-{1}-{2}', matrix.otp, matrix.elixir, hashFiles('mix.exs')) }}"
          restore-keys: "${{ format('test-build-{0}-{1}-', matrix.otp, matrix.elixir) }}"
      - name: "Cache Dependencies"
        uses: actions/cache@v4
        with:
          path: deps
          key: "${{ format('test-deps-{0}-{1}-{2}', matrix.otp, matrix.elixir, hashFiles('mix.exs')) }}"
          restore-keys: "${{ format('test-deps-{0}-{1}-', matrix.otp, matrix.elixir) }}"
      - name: "Cache Zig Binary"
        uses: actions/cache@v4
        with:
          path: ~/.cache/zigler
          key: "${{ format('zigler-{0}', hashFiles('mix.exs')) }}"
          restore-keys: "zigler-"

      - name: "Install Dependencies"
        run: mix deps.get --check-locked

      - name: "Install Zig"
        run: mix zig.get

      - run: mix coveralls.multiple --type html --type github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: mix_test-coverage-${{ matrix.elixir }}
          path: cover/

  credo:
    name: mix credo

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: "Setup Runtime Environment"
        uses: ./.github/actions/setup-runtime-env
        id: setupRuntimeEnv

      - run: mix credo

  dialyxir:
    name: mix dialyzer

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: "Setup Runtime Environment"
        uses: ./.github/actions/setup-runtime-env
        id: setupRuntimeEnv

      - uses: ./.github/actions/setup-senzing-playground

      - name: "Cache Dialyzer PLT Files"
        uses: actions/cache@v4
        with:
          path: |
            ~/.mix/*.plt
            _build/dev/*.plt
            _build/dev/*.plt.hash
          key: "${{ format('mix_dialyzer-dialyzer-{0}-{1}', hashFiles('.tool-versions'), hashFiles('mix.exs')) }}"
          restore-keys: "${{ format('mix_dialyzer-dialyzer-{0}-', hashFiles('.tool-versions')) }}"

      - run: mix dialyzer
