on:
  workflow_call: {}

name: "Test"

jobs:
  detectToolVersions:
    name: "Detect Tool Versions"

    runs-on: ubuntu-latest

    outputs:
      otpVersion: "${{ steps.toolVersions.outputs.OTP_VERSION }}"
      elixirVersion: "${{ steps.toolVersions.outputs.ELIXIR_VERSION }}"

    steps:
      - uses: actions/checkout@v4
      - name: "Read .tool-versions"
        id: toolVersions
        run: |
          OTP_VERSION="$(cat .tool-versions | grep erlang | cut -d' ' -f2-)"
          echo OTP: $OTP_VERSION
          echo "OTP_VERSION=${OTP_VERSION}" >> $GITHUB_OUTPUT

          ELIXIR_VERSION="$(cat .tool-versions | grep elixir | cut -d' ' -f2-)"
          echo Rebar: $ELIXIR_VERSION
          echo "ELIXIR_VERSION=${ELIXIR_VERSION}" >> $GITHUB_OUTPUT

  mix_format:
    name: mix format

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        with:
          path:  |
            _build
            priv/lib
          key: mix_format-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            mix_format-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - uses: actions/cache@v4
        with:
          path: deps
          key: mix_format-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            mix_format-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - run: mix format --check-formatted

  mix_test:
    name: mix test (${{ matrix.elixir }})

    runs-on: ubuntu-latest

    needs: ["detectToolVersions"]

    strategy:
      fail-fast: false
      matrix:
        include:
          # Lowest Supported Version
          - elixir: "1.17.0"
            otp: "27.0"
            unstable: false
          # Latest Supported Version (via ASDF)
          - elixir: "${{ needs.detectToolVersions.outputs.elixirVersion }}"
            otp: "${{ needs.detectToolVersions.outputs.otpVersion }}"
            unstable: false
          # Elixir Main
          - elixir: "main"
            otp: "${{ needs.detectToolVersions.outputs.otpVersion }}"
            unstable: true

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          otp-version: "${{ matrix.otp }}"
          elixir-version: "${{ matrix.elixir }}"
          version-type: strict
      - uses: ./.github/actions/setup-senzing-playground
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - uses: actions/cache@v4
        with:
          path:  |
            _build
            priv/lib
          key: mix_test-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            mix_test-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - uses: actions/cache@v4
        with:
          path: deps
          key: mix_test-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            mix_test-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - run: mix coveralls.multiple --type html --type github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: mix_test-coverage-${{ matrix.elixir }}
          path: cover/

  credo:
    name: mix credo

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        with:
          path:  |
            _build
            priv/lib
          key: credo-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            credo-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - uses: actions/cache@v4
        with:
          path: deps
          key: credo-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            credo-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - run: mix credo

  dialyxir:
    name: mix dialyzer

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: ./.github/actions/setup-senzing-playground
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - uses: actions/cache@v4
        with:
          path:  |
            _build
            priv/lib
          key: dialyxir-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            dialyxir-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - uses: actions/cache@v4
        with:
          path: deps
          key: dialyxir-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            dialyxir-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - run: mix dialyzer
