on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

name: "Stable Tag"

jobs:
  release:
    name: "Release"

    uses: ./.github/workflows/part_release.yml
    with:
      releaseName: "${{ github.ref_name }}"
      stable: true

  docs:
    name: "Docs"

    needs: ["release"]

    uses: ./.github/workflows/part_docs.yml
    with:
      releaseName: "${{ github.ref_name }}"

  publish:
    name: "Publish"

    needs: ["release"]

    uses: ./.github/workflows/part_publish.yml
    with:
      releaseName: "${{ github.ref_name }}"
    secrets:
      HEX_API_KEY: "${{ secrets.HEX_API_KEY }}"
